export enum ChaosToken {
  UNKNOWN,
  PLUS_ONE = "+1",
  ZERO = "0",
  MINUS_ONE = "-1",
  MINUS_TWO = "-2",
  MINUS_THREE = "-3",
  MINUS_FOUR = "-4",
  MINUS_FIVE = "-5",
  MINUS_SIX = "-6",
  MINUS_SEVEN = "-7",
  MINUS_EIGHT = "-8",
  ELDER_SIGN = "Elder Sign",
  AUTO_FAIL = "Auto Fail",
  SKULL = "Skull",
  CULTIST = "Cultist",
  TOMBSTONE = "Tombstone",
  TENTACLES = "Tentacles",
}
