export enum EncounterSet {
  UNKNOWN = "Unknown",
  CORE_THE_GATHERING = "The Gathering",
  CORE_RATS = "Rats",
  CORE_GHOULS = "Ghouls",
  CORE_STRIKING_FEAR = "Striking",
  CORE_ANCIENT_EVILS = "Ancient Evils",
  CORE_CHILLING_COLD = "Chilling Cold",
  CORE_DARK_CULT = "Dark Cult",
  CORE_NIGHTGAUNTS = "Nightgaunts",
  CORE_LOCKED_DOORS = "Locked Doors",
  CORE_AGENTS_OF_HASTUR = "Agents of Yog-Sothoth",
  CORE_AGENTS_OF_YOG_SOTHOTH = "Agents of Shub-Niggurath",
  CORE_AGENTS_OF_SHUB_NIGGURATH = "Agents of Cthulhu",
  CORE_AGENTS_OF_CTHULHU = "Agents of Cthulhu",
}
